import Navbar from "@/components/Navbar"
import { AppProvider } from "@/context/useAppContext"
import type { Metadata } from "next"
import { Toaster } from "sonner"
import "./globals.css"
import { ReactQueryProvider } from "./provider/TanstackQueryProvider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="flex h-screen flex-col" suppressHydrationWarning>
        <ReactQueryProvider>
          <AppProvider>
            <Navbar />
            {children}
            <Toaster richColors />
          </AppProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
