import type { Metadata } from "next"
import { cookies } from "next/headers"
import { Toaster } from "sonner"
import Navbar from "./components/Navbar"
import "./globals.css"
import { ReactQueryProvider } from "./provider/TanstackQueryProvider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const token = cookieStore.get("token")
  const userId = cookieStore.get("userId")?.value || ""
  const isAuthenticated = !!token
  const tokenValue = token?.value || ""

  return (
    <html lang="en">
      <body className="flex h-screen flex-col" suppressHydrationWarning>
        <ReactQueryProvider>
          <Navbar isAuthenticated={isAuthenticated} userId={userId} tokenValue={tokenValue} />
          {children}
          <Toaster richColors />
        </ReactQueryProvider>
      </body>
    </html>
  )
}
